services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      # - <port on localhost>:<port on container>
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/liv/postgresql/data

volumes:
  postgres-db: