services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - <port on localhost>:<port on container>
      - 8000:8000
    env_file:
      - ./.env
  # postgres:
  #   image: 
  #   environment:
  #     - POSTGRES_PASSWORD=value
  #     - POSTGRES_DB=