name: Build and Deploy code

on:
    push:
        branches:
            - main

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Echo OK
              run: echo "OK"
            - name: Setup Python
              uses: actions/setup-python@v5.4.0
              with:
                python-version: "3.13.2"
            - name: Updated Pip
              run: python -m pip install --upgrade pip
            - name: Install Dependencies
              run: pip install -r requirements.txt